version: "3.9"

networks:
  plot_net:
    name: plot_net

services:
  server:
    build:
      context: ./server
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    networks:
      - plot_net

  client:
    build:
      context: ./client
      dockerfile: ./client/Dockerfile
    env_file:
      - .env
    networks:
      - plot_net
    depends_on:
      - server