version: "3.9"

networks:
  plot_net:
    name: plot_net

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - plot_net

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    env_file:
      - .env
    networks:
      - plot_net
    depends_on:
      - server