# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import grpc_plotter_pb2 as grpc__plotter__pb2


class PlotterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNextPoint = channel.unary_unary(
                '/Plotter/GetNextPoint',
                request_serializer=grpc__plotter__pb2.Request.SerializeToString,
                response_deserializer=grpc__plotter__pb2.Point.FromString,
                )


class PlotterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNextPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlotterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNextPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextPoint,
                    request_deserializer=grpc__plotter__pb2.Request.FromString,
                    response_serializer=grpc__plotter__pb2.Point.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Plotter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Plotter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNextPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Plotter/GetNextPoint',
            grpc__plotter__pb2.Request.SerializeToString,
            grpc__plotter__pb2.Point.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
